ignite:
  partition:
    count: 256
  ds:
    base: /var/ignite/ds
    wal: ${ignite.ds.base}/wal
    wal-arch: ${ignite.ds.base}/wal-arch
    storage: ${ignite.ds.base}/storage

  cache:
    my_cache:
      preload: 100
      rebuild: false

management:
  security:
    enabled: false

consul:
  url: ${consul_url:localhost"}
  tags:
    - 'MSK'
    - 'server-node'

server:
  port: ${http_port:28080}