version: '2.1'

services:

  elk:
    image: sebp/elk:600
    network_mode: "host"
    volumes:
      - "./03-tcp-input.conf:/etc/logstash/conf.d/03-tcp-input.conf"
      - "./30-output.conf:/etc/logstash/conf.d/30-output.conf"