version: '2.1'

services:
  zookeeper:
    image: zookeeper:3.5.3-beta
    network_mode: "host"

  master:
    image: mesosphere/mesos-master:1.4.0
    depends_on:
      - zookeeper
    environment:
      - MESOS_ZK=zk://localhost:2181/mesos
      - MESOS_PORT=5050
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_LOGGING_LEVEL=INFO
    network_mode: "host"

  slave:
    image: mesosphere/mesos-slave:1.4.0
    depends_on:
      - zookeeper
    network_mode: "host"
    entrypoint:
      - mesos-slave
    privileged: true
    volumes:
      - "/usr/local/bin/docker:/usr/local/bin/docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - MESOS_MASTER=zk://localhost:2181/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_ISOLATION=posix/cpu,posix/mem

  marathon:
    image: mesosphere/marathon:v1.5.2
    restart: on-failure
    depends_on:
      - zookeeper
      - master
    network_mode: "host"
    command: --master zk://localhost:2181/mesos --zk zk://localhost:2181/marathon --http_port 8081

  marathon-lb:
    image: mesosphere/marathon-lb:v1.8.1
    depends_on:
      - marathon
    environment:
      - PORTS=80,443,9090,9091
    network_mode: "host"
    command: sse --marathon http://localhost:8081 --group external --health-check
