---
apiVersion: v1
kind: Service
metadata:
  name: ignite
spec:
  type:	NodePort
  ports:
    - port: 28080
      nodePort: 30300
  selector:
    app: ignite-showcase


---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ignite-showcase
  labels:
    app: ignite-showcase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ignite-showcase
  template:
    metadata:
      labels:
        app: ignite-showcase
    spec:
      containers:
      - name: ignite-showcase
        imagePullPolicy: Never
        image: codeunited/ignite-showcase:1.0.0
        ports:
          - containerPort: 28080
          - containerPort: 11211
          - containerPort: 47100
          - containerPort: 47500
          - containerPort: 49112
