version: '2.1'

services:

  prometheus:
    image: prom/prometheus:v2.0.0
    network_mode: "host"
    ports:
      - "29090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"